### ISSUE TITLE
这个功能和IPFS本身的网关一样吗

### ISSUE THREAD

**Issue by xuruijing** [linonetwo/ipfs-browser-gateway#2]
我试了一下这个代码，运行结果好像没有正确的输出。
http://localhost:3000/ipfs/QmSY6Y3sgev6DSbvn6E543nW3cmdwe7ezuzukEZKuWVGrM
后面的hashCode换成任何一个，页面都是显示这个hashCode，这应该是不对的吧

Compiled successfully!

You can now view ipfs-browser-gateway in the browser.

  Local:            http://localhost:3000/
  On Your Network:  http://192.168.1.10:3000/

Note that the development build is not optimized.
To create a production build, use yarn build.

**Comment by linonetwo** [comment]
Sure they should be the same.

But before going to http://localhost:3000/ipfs/QmSY6Y3sgev6DSbvn6E543nW3cmdwe7ezuzukEZKuWVGrM, you need to visit http://localhost:3000 first. So that service worker can install properly.

Was your service worker installed properly?

**Comment by xuruijing** [comment]
我是先访问 http://localhost:3000，然后在页面点击链接访问http://localhost:3000/ipfs/QmSY6Y3sgev6DSbvn6E543nW3cmdwe7ezuzukEZKuWVGrM，这个过程和你说的一样的，但是我不确定service worker是否正常，如何确定？

**Comment by linonetwo** [comment]
I've made some bugfix, please try the latest version. But IPFS is not stable due to GFW. It works on my side, closing this.
